# Generated by Django 4.2.9 on 2026-06-02 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0002_alter_alerta_fecha_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='estado',
            field=models.CharField(choices=[('normal', 'Normal'), ('alerta', 'Alerta'), ('critico', 'Crítico')], default='normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='fecha_activacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registrosalud',
            name='movimiento',
            field=models.CharField(default='estable', max_length=50),
        ),
        migrations.AlterField(
            model_name='sesionsueno',
            name='hora_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
